### ISSUE TITLE
Aws\S3\S3Client not found

### ISSUE THREAD

**Issue by ivagarfitt** [arkadedigital/magento2-s3#30]
Hi, I am getting this error:

`[proxy_fcgi:error] [pid 8421:tid 139754989307648] [client 127.0.0.1:44479] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'Aws\\S3\\S3Client' not found in /opt/bitnami/apps/magento/htdocs/app/code/Arkade/S3/Model/MediaStorage/File/Storage/S3.php:59\nStack trace:\n#0 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Arkade\\S3\\Model\\MediaStorage\\File\\Storage\\S3->__construct(Object(Arkade\\S3\\Helper\\Data), Object(Magento\\MediaStorage\\Helper\\File\\Media), Object(Magento\\MediaStorage\\Helper\\File\\Storage\\Database\\Interceptor), Object(Magento\\Framework\\Logger\\Monolog))\n#1 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Arkade\\\\S3\\\\Model...', Array)\n#2 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Arkade\\\\S3\\\\Model...', Array)\n#3 /opt/bitnami/apps/magento/htdocs/var/generation/Arkade/S3/Mode...\n'`

**Comment by edelgonzalez** [comment]
you might need to reinstall aws-sdk-php

composer require aws/aws-sdk-php
